image:
  repository: docker.elastic.co/observability-ci/apm-mutating-webhook
  tag: latest
  pullPolicy: Always
  pullSecrets: []

certFile: cert.pem
keyFile: key.pem
apm:
  namespaces:
    - default
  token:

replicaCount: 1

service:
  port: 443

container:
  port: 8443

podAnnotations: {}
podLabels: {}

webhookConfig:
  agents:
    java:
      image: docker.elastic.co/observability/apm-agent-java:1.30.1
      artifact: "/usr/agent/elastic-apm-agent.jar"
      environment:
        JAVA_TOOL_OPTIONS: "-javaagent:/elastic/apm/agent/elastic-apm-agent.jar"
